apiVersion: release-notes/v2

kind: feature
area: telemetry
issue:
- 37665

releaseNotes:
- |
    **Added** controls for matching based on WorkloadMode to logging and tracing
    configuration to the Telemetry API.

# docs is a list of related docs to the change.
docs:
- https://docs.google.com/document/d/1pTFVzGii7sB4uALMsrUN4ALFc0J7vI2UyBnJpP_bsgU/edit
