apiVersion: release-notes/v2
kind: feature
area: documentation
issue:
  - https://github.com/istio/istio/pull/34832
releaseNotes:
  - |
    **Added** sidecar `traffic.sidecar.istio.io/excludeInterfaces` annotation documentation.
