apiVersion: release-notes/v2
kind: feature
area: security
issue:
  - https://github.com/istio/istio/issues/32502

releaseNotes:
  - |
    **Added** Add MultiRootCA  to mesh config to allow workloads using different root ca for mTLS
