# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/v1beta1/selector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btype/v1beta1/selector.proto\x12\x12istio.type.v1beta1\x1a\x1fgoogle/api/field_behavior.proto\"\xb2\x01\n\x10WorkloadSelector\x12^\n\x0cmatch_labels\x18\x01 \x03(\x0b\x32\x35.istio.type.v1beta1.WorkloadSelector.MatchLabelsEntryB\x04\xe2\x41\x01\x02R\x0bmatchLabels\x1a>\n\x10MatchLabelsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\x1bZ\x19istio.io/api/type/v1beta1b\x06proto3')



_WORKLOADSELECTOR = DESCRIPTOR.message_types_by_name['WorkloadSelector']
_WORKLOADSELECTOR_MATCHLABELSENTRY = _WORKLOADSELECTOR.nested_types_by_name['MatchLabelsEntry']
WorkloadSelector = _reflection.GeneratedProtocolMessageType('WorkloadSelector', (_message.Message,), {

  'MatchLabelsEntry' : _reflection.GeneratedProtocolMessageType('MatchLabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : _WORKLOADSELECTOR_MATCHLABELSENTRY,
    '__module__' : 'type.v1beta1.selector_pb2'
    # @@protoc_insertion_point(class_scope:istio.type.v1beta1.WorkloadSelector.MatchLabelsEntry)
    })
  ,
  'DESCRIPTOR' : _WORKLOADSELECTOR,
  '__module__' : 'type.v1beta1.selector_pb2'
  # @@protoc_insertion_point(class_scope:istio.type.v1beta1.WorkloadSelector)
  })
_sym_db.RegisterMessage(WorkloadSelector)
_sym_db.RegisterMessage(WorkloadSelector.MatchLabelsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031istio.io/api/type/v1beta1'
  _WORKLOADSELECTOR_MATCHLABELSENTRY._options = None
  _WORKLOADSELECTOR_MATCHLABELSENTRY._serialized_options = b'8\001'
  _WORKLOADSELECTOR.fields_by_name['match_labels']._options = None
  _WORKLOADSELECTOR.fields_by_name['match_labels']._serialized_options = b'\342A\001\002'
  _WORKLOADSELECTOR._serialized_start=85
  _WORKLOADSELECTOR._serialized_end=263
  _WORKLOADSELECTOR_MATCHLABELSENTRY._serialized_start=201
  _WORKLOADSELECTOR_MATCHLABELSENTRY._serialized_end=263
# @@protoc_insertion_point(module_scope)
