pull_request_rules:
  - name: Automatically cherry pick a PR from master to the release branch if the right label is set
    conditions:
      - base=master
      - label=action/merge-to-release-branch
    actions:
      backport:
        branches:
          - release-1.2
