// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mcp/v1alpha1/resource.proto

// This package defines the common, core types used by the Mesh Configuration Protocol.

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Resource as transferred via the Mesh Configuration Protocol. Each
// resource is made up of common metadata, and a type-specific resource payload.
type Resource struct {
	// Common metadata describing the resource.
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The primary payload for the resource.
	Body                 *any.Any `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_d75ce896e5708e1a, []int{0}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Resource) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Resource)(nil), "istio.mcp.v1alpha1.Resource")
}

func init() { proto.RegisterFile("mcp/v1alpha1/resource.proto", fileDescriptor_d75ce896e5708e1a) }

var fileDescriptor_d75ce896e5708e1a = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0x4d, 0x2e, 0xd0,
	0x2f, 0x33, 0x4c, 0xcc, 0x29, 0xc8, 0x48, 0x34, 0xd4, 0x2f, 0x4a, 0x2d, 0xce, 0x2f, 0x2d, 0x4a,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xca, 0x2c, 0x2e, 0xc9, 0xcc, 0xd7, 0xcb,
	0x4d, 0x2e, 0xd0, 0x83, 0x29, 0x91, 0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0xab,
	0x48, 0x2a, 0x4d, 0xd3, 0x4f, 0xcc, 0xab, 0x84, 0x28, 0x97, 0x42, 0x35, 0x2b, 0x37, 0xb5, 0x24,
	0x31, 0x25, 0xb1, 0x24, 0x11, 0x22, 0xa9, 0x94, 0xc7, 0xc5, 0x11, 0x04, 0x35, 0x5d, 0xc8, 0x82,
	0x8b, 0x03, 0x26, 0x2b, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa3, 0x87, 0x69, 0x95, 0x9e,
	0x2f, 0x54, 0x4d, 0x10, 0x5c, 0xb5, 0x90, 0x06, 0x17, 0x4b, 0x52, 0x7e, 0x4a, 0xa5, 0x04, 0x13,
	0x58, 0x97, 0x88, 0x1e, 0xc4, 0x31, 0x7a, 0x30, 0xc7, 0xe8, 0x39, 0xe6, 0x55, 0x06, 0x81, 0x55,
	0x38, 0x49, 0x47, 0x49, 0x42, 0x8c, 0xcc, 0xcc, 0xd7, 0x4f, 0x2c, 0xc8, 0xd4, 0x47, 0x76, 0x5b,
	0x12, 0x1b, 0x58, 0x83, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x35, 0x55, 0xe2, 0xfe, 0x00,
	0x00, 0x00,
}
