version: 2
defaults: &defaults
  working_directory: /src/istio.io/api
  docker:
    - image: gcr.io/istio-testing/protoc:2018-06-12
  environment:
    GOPATH: /go
    OUT_PATH: /src

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            ./scripts/generate-protos.sh || die "could not generate *.pb.go"
            if [[ -n $(git status --porcelain) ]]; then
              git status
              git --no-pager diff
              echo "Repo has unstaged changes. Re-run ./scripts/generate-protos.sh"
              exit 1
            fi

workflows:
  version: 2
  all:
    jobs:
      - build
