// Code generated by protoc-gen-go. DO NOT EDIT.
// source: routing/v1alpha2/foreign_service.proto

package istio_routing_v1alpha2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Different ways of discovering the IP addresses associated with the
// service.
type ForeignService_Discovery int32

const (
	// If set to "none", the proxy will assume that incoming connections
	// have already been resolved (to a specific destination IP
	// address). Such connections are typically routed via the proxy using
	// mechanisms such as IP table REDIRECT/ eBPF. After performing any
	// routing related transformations, the proxy will forward the
	// connection to the IP address to which the connection was bound.
	ForeignService_NONE ForeignService_Discovery = 0
	// If set to "static", the proxy will use the IP addresses specified in
	// endpoints (See below) as the backing nodes associated with the
	// foreign service.
	ForeignService_STATIC ForeignService_Discovery = 1
	// If set to "dns", the proxy will attempt to resolve the DNS address
	// during request processing. If no endpoints are specified, the proxy
	// will resolve the DNS address specified in the hosts field, if
	// wildcards are not used. If endpoints are specified, the DNS
	// addresses specified in the endpoints will be resolved to determine
	// the destination IP address.
	ForeignService_DNS ForeignService_Discovery = 2
)

var ForeignService_Discovery_name = map[int32]string{
	0: "NONE",
	1: "STATIC",
	2: "DNS",
}
var ForeignService_Discovery_value = map[string]int32{
	"NONE":   0,
	"STATIC": 1,
	"DNS":    2,
}

func (x ForeignService_Discovery) String() string {
	return proto.EnumName(ForeignService_Discovery_name, int32(x))
}
func (ForeignService_Discovery) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 0} }

// Foreign service describes the endpoints, ports and protocols of a
// white-listed set of mesh-external domains and IP blocks that services in
// the mesh are allowed to access.
//
// For example, the following foreign service configuration describes the
// set of services at https://example.com to be accessed internally over
// plaintext http (i.e. http://example.com:443), with the sidecar originating
// TLS.
//
//     apiVersion: config.istio.io/v1alpha2
//     kind: ForeignService
//     metadata:
//       name: foreign-svc-example
//     spec:
//       hosts:
//       - example.com
//       ports:
//       - number: 443
//         name: example-http
//         protocol: http # not HTTPS.
//       discovery: dns
//
// and a destination rule to initiate TLS connections to the external service.
//
//     apiVersion: config.istio.io/v1alpha2
//     kind: DestinationRule
//     metadata:
//       name: tls-example
//     spec:
//       destination:
//         name: example.com
//       tls:
//         mode: simple # initiates HTTPS when talking to example.com
//
// The following specification specifies a static set of backend nodes for
// a MongoDB cluster behind a set of virtual IPs, and sets up a destination
// rule to initiate mTLS connections upstream.
//
//     apiVersion: config.istio.io/v1alpha2
//     kind: ForeignService
//     metadata:
//       name: foreign-svc-mongocluster
//     spec:
//       hosts:
//       - 192.192.192.192/24
//       ports:
//       - number: 27018
//         name: mongodb
//         protocol: mongo
//       discovery: static
//       endpoints:
//       - address: 2.2.2.2
//       - address: 3.3.3.3
//
// and the associated destination rule
//
//     apiVersion: config.istio.io/v1alpha2
//     kind: DestinationRule
//     metadata:
//       name: mtls-mongocluster
//     spec:
//       destination:
//         name: 192.192.192.192/24
//       tls:
//         mode: mutual
//         clientCertificate: /etc/certs/myclientcert.pem
//         privateKey: /etc/certs/client_private_key.pem
//         caCertificates: /etc/certs/rootcacerts.pem
//
// The following example demonstrates the use of wildcards in the hosts. If
// the connection has to be routed to the IP address requested by the
// application (i.e. application resolves DNS and attempts to connect to a
// specific IP), the discovery mode must be set to "none".
//
//     apiVersion: config.istio.io/v1alpha2
//     kind: ForeignService
//     metadata:
//       name: foreign-svc-wildcard-example
//     spec:
//       hosts:
//       - *.bar.com
//       ports:
//       - number: 80
//         name: http
//         protocol: http
//       discovery: none
//
// For HTTP based services, it is possible to create a virtual service
// backed by multiple DNS addressible endpoints. In such a scenario, the
// application can use the HTTP_PROXY environment variable to transparently
// reroute API calls for the virtual service to a chosen backend. For
// example, the following configuration creates a non-existent service
// called foo.bar.com backed by three domains: us.foo.bar.com:8443,
// uk.foo.bar.com:9443, and in.foo.bar.com:7443
//
//     apiVersion: config.istio.io/v1alpha2
//     kind: ForeignService
//     metadata:
//       name: foreign-svc-dns
//     spec:
//       hosts:
//       - foo.bar.com
//       ports:
//       - number: 443
//         name: https
//         protocol: http
//       discovery: dns
//       endpoints:
//       - address: us.foo.bar.com
//         ports:
//         - https: 8443
//       - address: uk.foo.bar.com
//         ports:
//         - https: 9443
//       - address: in.foo.bar.com
//         ports:
//         - https: 7443
//
// and a destination rule to initiate TLS connections to the external service.
//
//     apiVersion: config.istio.io/v1alpha2
//     kind: DestinationRule
//     metadata:
//       name: tls-foobar
//     spec:
//       destination:
//         name: foo.bar.com
//       tls:
//         mode: simple # initiates HTTPS
//
// With HTTP_PROXY=http://localhost:443, calls from the application to
// http://foo.bar.com will be upgraded to HTTPS and load balanced across
// the three domains specified above. In other words, a call to
// http://foo.bar.com/baz would be translated to
// https://uk.foo.bar.com/baz.
//
// NOTE: In the scenario above, the value of the HTTP Authority/host header
// associated with the outbound HTTP requests will be based on the
// endpoint's DNS name, i.e. ":authority: uk.foo.bar.com". Refer to Envoy's
// auto_host_rewrite for further details. The automatic rewrite can be
// overridden using a host rewrite route rule.
//
type ForeignService struct {
	// REQUIRED. The hosts associated with the external service. Could be a
	// DNS name with wildcard prefix or a CIDR prefix. Note that the hosts
	// field applies to all protocols. DNS names in hosts will be ignored if
	// the application accesses the service over non-HTTP protocols such as
	// mongo/opaque TCP/even HTTPS. In such scenarios, the port on which the
	// external service is being accessed must not be shared by any other
	// service in the mesh. In other words, the sidecar will behave as a
	// simple TCP proxy, forwarding incoming traffic on a specified port to
	// the specified destination endpoint IP/host.
	Hosts []string `protobuf:"bytes,1,rep,name=hosts" json:"hosts,omitempty"`
	// REQUIRED. The ports associated with the external service.
	Ports []*Port `protobuf:"bytes,2,rep,name=ports" json:"ports,omitempty"`
	// Service discovery mode for the hosts. If not set, Istio will attempt
	// to infer the discovery mode based on the value of hosts and endpoints.
	Discovery ForeignService_Discovery `protobuf:"varint,3,opt,name=discovery,enum=istio.routing.v1alpha2.ForeignService_Discovery" json:"discovery,omitempty"`
	// One or more endpoints associated with the service. Endpoints must be
	// accessible over the set of outPorts defined at the service level.
	Endpoints []*ForeignService_Endpoint `protobuf:"bytes,4,rep,name=endpoints" json:"endpoints,omitempty"`
}

func (m *ForeignService) Reset()                    { *m = ForeignService{} }
func (m *ForeignService) String() string            { return proto.CompactTextString(m) }
func (*ForeignService) ProtoMessage()               {}
func (*ForeignService) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *ForeignService) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *ForeignService) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ForeignService) GetDiscovery() ForeignService_Discovery {
	if m != nil {
		return m.Discovery
	}
	return ForeignService_NONE
}

func (m *ForeignService) GetEndpoints() []*ForeignService_Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

// Endpoint defines a network address (IP or hostname) associated with
// the foreign service.
type ForeignService_Endpoint struct {
	// REQUIRED: Address associated with the network endpoint without the
	// port ( IP or fully qualified domain name without wildcards).
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	// Set of ports associated with the endpoint. The ports must be
	// associated with a port name that was declared as part of the
	// service.
	Ports map[string]uint32 `protobuf:"bytes,2,rep,name=ports" json:"ports,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// One or more labels associated with the endpoint.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ForeignService_Endpoint) Reset()                    { *m = ForeignService_Endpoint{} }
func (m *ForeignService_Endpoint) String() string            { return proto.CompactTextString(m) }
func (*ForeignService_Endpoint) ProtoMessage()               {}
func (*ForeignService_Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 0} }

func (m *ForeignService_Endpoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ForeignService_Endpoint) GetPorts() map[string]uint32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ForeignService_Endpoint) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*ForeignService)(nil), "istio.routing.v1alpha2.ForeignService")
	proto.RegisterType((*ForeignService_Endpoint)(nil), "istio.routing.v1alpha2.ForeignService.Endpoint")
	proto.RegisterEnum("istio.routing.v1alpha2.ForeignService_Discovery", ForeignService_Discovery_name, ForeignService_Discovery_value)
}

func init() { proto.RegisterFile("routing/v1alpha2/foreign_service.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0x80, 0x6f, 0x92, 0xfe, 0xe5, 0x94, 0x5b, 0xc2, 0x70, 0xb9, 0x84, 0x70, 0xb9, 0x84, 0x2e,
	0x24, 0xb8, 0x48, 0x35, 0x6e, 0x6a, 0x5d, 0x89, 0xad, 0x20, 0x68, 0x2c, 0x49, 0xf7, 0x92, 0x36,
	0x63, 0x3b, 0x18, 0x32, 0x61, 0x66, 0x1a, 0xc9, 0xdb, 0xf9, 0x38, 0x3e, 0x86, 0x34, 0x93, 0xd8,
	0x16, 0x15, 0xed, 0x2e, 0x27, 0x9c, 0xef, 0x3b, 0x7f, 0x03, 0x47, 0x8c, 0xae, 0x05, 0x49, 0x97,
	0x83, 0xfc, 0x34, 0x4a, 0xb2, 0x55, 0xe4, 0x0d, 0x1e, 0x29, 0xc3, 0x64, 0x99, 0x3e, 0x70, 0xcc,
	0x72, 0xb2, 0xc0, 0x6e, 0xc6, 0xa8, 0xa0, 0xe8, 0x2f, 0xe1, 0x82, 0x50, 0xb7, 0xca, 0x76, 0xeb,
	0x6c, 0xeb, 0xff, 0x07, 0x7e, 0x19, 0x09, 0xfc, 0x1c, 0x15, 0x92, 0xeb, 0xbf, 0x36, 0xa0, 0x77,
	0x2d, 0x8d, 0xa1, 0x14, 0xa2, 0x3f, 0xd0, 0x5c, 0x51, 0x2e, 0xb8, 0xa9, 0xd8, 0x9a, 0xa3, 0x07,
	0x32, 0x40, 0x1e, 0x34, 0x33, 0xca, 0x04, 0x37, 0x55, 0x5b, 0x73, 0xba, 0xde, 0x3f, 0xf7, 0xf3,
	0x82, 0xee, 0x94, 0x32, 0x11, 0xc8, 0x54, 0xe4, 0x83, 0x1e, 0x13, 0xbe, 0xa0, 0x39, 0x66, 0x85,
	0xa9, 0xd9, 0x8a, 0xd3, 0xf3, 0x4e, 0xbe, 0xe2, 0xf6, 0x9b, 0x70, 0xc7, 0x35, 0x17, 0x6c, 0x15,
	0xe8, 0x0e, 0x74, 0x9c, 0xc6, 0x19, 0x25, 0xa9, 0xe0, 0x66, 0xa3, 0xec, 0x63, 0xf0, 0x43, 0xdf,
	0xa4, 0xe2, 0x82, 0xad, 0xc1, 0x7a, 0x51, 0xa1, 0x53, 0xff, 0x47, 0x26, 0xb4, 0xa3, 0x38, 0x66,
	0x98, 0x6f, 0xe6, 0x56, 0x1c, 0x3d, 0xa8, 0x43, 0x34, 0xdd, 0x9f, 0x7c, 0x74, 0x60, 0xc5, 0x72,
	0x23, 0x7c, 0x92, 0x0a, 0x56, 0xd4, 0x7b, 0x09, 0xa1, 0x95, 0x44, 0x73, 0x9c, 0x70, 0x53, 0x2b,
	0x95, 0x17, 0x87, 0x2a, 0x6f, 0x4b, 0x5a, 0x3a, 0x2b, 0x95, 0x35, 0x04, 0xd8, 0x56, 0x42, 0x06,
	0x68, 0x4f, 0xb8, 0xa8, 0x46, 0xd9, 0x7c, 0x6e, 0xce, 0x9a, 0x47, 0xc9, 0x1a, 0x9b, 0xaa, 0xad,
	0x38, 0xbf, 0x03, 0x19, 0x8c, 0xd4, 0xa1, 0x62, 0x9d, 0x43, 0x77, 0x47, 0xf8, 0x1d, 0xaa, 0xef,
	0xa0, 0xfd, 0x63, 0xd0, 0xdf, 0x2f, 0x85, 0x3a, 0xd0, 0xf0, 0xef, 0xfd, 0x89, 0xf1, 0x0b, 0x01,
	0xb4, 0xc2, 0xd9, 0xe5, 0xec, 0xe6, 0xca, 0x50, 0x50, 0x1b, 0xb4, 0xb1, 0x1f, 0x1a, 0xea, 0xbc,
	0x55, 0xbe, 0xb8, 0xb3, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xf0, 0x1a, 0x2a, 0xd3, 0x02,
	0x00, 0x00,
}
