// Code generated by protoc-gen-go. DO NOT EDIT.
// source: routing/v1alpha2/route_rule.proto

package istio_routing_v1alpha2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/duration"
import google_protobuf1 "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ### Glossary & concepts
//
// *Service* is a unit of an application with a unique name that other services
// use to refer to the functionality being called. Service instances are
// pods/VMs/containers that implement the service.
//
// *Service versions* - In a continuous deployment scenario, for a given service,
// there can be multiple sets of instances running potentially different
// variants of the application binary. These variants are not necessarily
// different API versions. They could be iterative changes to the same service,
// deployed in different environments (prod, staging, dev, etc.). Common
// scenarios where this occurs include A/B testing, canary rollouts, etc. The
// choice of a particular version can be decided based on various criterion
// (headers, url, etc.) and/or by weights assigned to each version.  Each
// service has a default version consisting of all its instances.
//
// *Source* - downstream client (browser or another service) calling the
// Envoy proxy/sidecar (typically to reach another service).
//
// *Host* - The remote upstream service to which the Envoy proxy/sidecar is
// talking to, on behalf of the source service. There can be one or more
// service versions for a given service (see the discussion on versions above).
// Envoy would choose the version based on various routing rules.
//
// *Access model* - Applications address only the destination service (Host)
// without knowledge of individual service versions. The actual choice of
// the version is determined by Envoy, enabling the application code to
// decouple itself from the evolution of dependent services.
//
//
//
// Route rule provides a custom routing policy based on the source and
// destination service versions and connection/request metadata.  The rule
// must provide a set of conditions for each protocol (TCP, UDP, HTTP) that
// the destination service exposes on its ports.
//
// The rule applies only to the ports on the destination service for which
// it provides protocol-specific match condition, e.g. if the rule does not
// specify TCP condition, the rule does not apply to TCP traffic towards
// the destination service.
//
// For example, the following rule routes all traffic by default to pods of
// reviews service with label "version: v1". In addition, HTTP requests
// containing for /api/v2/ url prefix will be sent to pods
// with label version: v2.
//
//     metadata:
//       name: my-rule
//       namespace: default # optional (default is "default")
//     spec:
//       hosts:
//         - reviews
//       http:
//         - match:
//           - uri:
//               prefix: "/api/v2"
//           route:
//           - destination:
//               labels:
//                 version: v2
//             weight: 100
//         - route:
//           - destination:
//               labels:
//                 version: v1
//             weight: 100
//
// Every service in the mesh can have utmost one route rule associated with
// it.  A single route rule can be used to describe traffic properties for
// multiple HTTP and TCP ports.
type RouteRule struct {
	// REQUIRED. The network destination for traffic described by this
	// routing rule. Could be a DNS name with wildcard prefix or a CIDR
	// prefix. Depending on the platform, plain service names can also be
	// used instead of a FQDN (i.e. has no dots in the name). In such a
	// scenario, the FQDN of the host would be derived based on the
	// underlying platform.
	//
	// For example on Kubernetes a client in the "default" namespace
	// referring to "reviews" would be resolved to the FQDN
	// "reviews.default.svc.cluster.local". However, a different name such as
	// "reviews.sales" would be treated as a FQDN during virtual host
	// matching.  In Consul, a plain service name would be resolved to the
	// FQDN "reviews.service.consul".
	//
	// Note that the hosts field applies to both HTTP and TCP services. In
	// case of TCP services, the plain service name or a IP address with CIDR
	// prefix can be used.
	Hosts []string `protobuf:"bytes,1,rep,name=hosts" json:"hosts,omitempty"`
	// Applies the route rule only to a specific set of workloads.
	// The rule is matched if any one of the sources match.
	Sources []*Source `protobuf:"bytes,2,rep,name=sources" json:"sources,omitempty"`
	// The named gateways to bind this route rule to.  If no names are
	// specified the default value is the reserved name "mesh" which
	// indicates that the rule should be applied to the internal mesh
	// network. It is fine for a rule to be bound to multiple named gateways
	// and "mesh" at the same time. It is also fine to refer to mesh
	// resources in other namespaces as long as the gateway permits the
	// binding per it's RBAC rules. This form implies that explicit binding
	// is required for route rules that impact how traffic enters or exits
	// the mesh.
	Gateways []string `protobuf:"bytes,3,rep,name=gateways" json:"gateways,omitempty"`
	// A list of routes for HTTP traffic
	Http []*HTTPRoute `protobuf:"bytes,4,rep,name=http" json:"http,omitempty"`
	// A lit of routes for TCP traffic.
	Tcp []*TCPRoute `protobuf:"bytes,5,rep,name=tcp" json:"tcp,omitempty"`
}

func (m *RouteRule) Reset()                    { *m = RouteRule{} }
func (m *RouteRule) String() string            { return proto.CompactTextString(m) }
func (*RouteRule) ProtoMessage()               {}
func (*RouteRule) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RouteRule) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *RouteRule) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *RouteRule) GetGateways() []string {
	if m != nil {
		return m.Gateways
	}
	return nil
}

func (m *RouteRule) GetHttp() []*HTTPRoute {
	if m != nil {
		return m.Http
	}
	return nil
}

func (m *RouteRule) GetTcp() []*TCPRoute {
	if m != nil {
		return m.Tcp
	}
	return nil
}

// Destination indicates the network addressable service or a workload name
// to which the request/connection will be sent after processing a routing
// rule.
type Destination struct {
	// One or more labels that constrain the applicability of a rule
	// to workloads with the given labels.
	Labels map[string]string `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The addressable service name. May be partially or fully qualified.
	// Partially qualified names are resolved in the context of the
	// client. Alternatively, it could also specify an IP address to which
	// the connection should be forwarded to. Labels will be applied to
	// select a subset of instances in the destination, to load balance
	// requests to. If an IP address is used for the host, labels will be
	// ignored. If the host is omitted, the host value from the route rule
	// would be used to determine the final destination. TODO: doc conflict
	// resolution
	//
	// For example on Kubernetes a client in the "default" namespace
	// referring to "reviews" would be resolved to the FQDN
	// "reviews.default.svc.cluster.local". Similarly a client in the default
	// namespace could add a namespace qualifier to the short name. For
	// instance "reviews.sales" would resolve to the reviews service in the
	// sales namespace, i.e. "reviews.sales.svc.cluster.local".
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	// Specifies the port on the destination. Many services only expose a
	// single port or label ports with the protocols they support, in these
	// cases it is not required to explicitly select the port. Note that
	// selection priority is to first match by name and then match by number.
	//
	// Names must comply with DNS label syntax (rfc1035) and therefore cannot
	// collide with numbers. If there are multiple ports on a service with the
	// same protocol the names should be of the form <protocol-name>-<DNS label>
	Port string `protobuf:"bytes,5,opt,name=port" json:"port,omitempty"`
}

func (m *Destination) Reset()                    { *m = Destination{} }
func (m *Destination) String() string            { return proto.CompactTextString(m) }
func (*Destination) ProtoMessage()               {}
func (*Destination) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Destination) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Destination) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Destination) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

// Describes a label constraint on the workloads where traffic originates.
// For example, the following snippet restricts the rule to match only
// requests originating from instances with label "version:v2".
//
//     metadata:
//       name: my-rule
//       namespace: default
//     spec:
//       hosts:
//         - ratings
//       sources:
//         - labels:
//             version: v2
//       http:
//         ...
type Source struct {
	// Workload name. Interpretation subject to the underlying platform
	// (e.g., app names in cloud foundry). ONLY ONE OF name or labels can
	// be specified.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// One or more labels that constrain the applicability of a rule to
	// workloads with the given labels. ONLY ONE OF name or labels can be
	// used.
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Source) Reset()                    { *m = Source{} }
func (m *Source) String() string            { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()               {}
func (*Source) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Source) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// Describes match conditions and actions for routing HTTP traffic.
type HTTPRoute struct {
	// Match conditions to be satisfied for the route rule to be
	// activated. All conditions inside a single match block have AND semantics,
	// while the list of match blocks have OR semantics. The rule is matched if
	// any one of the match blocks succeed.
	Match []*HTTPMatchRequest `protobuf:"bytes,1,rep,name=match" json:"match,omitempty"`
	// A routing rule can either redirect traffic or forward traffic
	// (default). The forwarding target can be one of several versions of a
	// service (see glossary in beginning of document). Weights associated
	// with the service version determine the proportion of traffic it
	// receives.
	Route []*DestinationWeight `protobuf:"bytes,2,rep,name=route" json:"route,omitempty"`
	// A routing rule can either redirect traffic or forward traffic. The
	// redirect primitive can be used to send a HTTP 302 redirect to a
	// different URI or Authority.
	Redirect *HTTPRedirect `protobuf:"bytes,3,opt,name=redirect" json:"redirect,omitempty"`
	// Rewrite HTTP URIs and Authority headers. Rewrite cannot be used with
	// Redirect primitive. Rewrite will be performed before forwarding.
	Rewrite *HTTPRewrite `protobuf:"bytes,4,opt,name=rewrite" json:"rewrite,omitempty"`
	// Indicates that a HTTP/1.1 client connection to this particular route
	// should be allowed (and expected) to upgrade to a WebSocket connection.
	// The default is false. Envoy expects the first request to this route
	// to contain the WebSocket upgrade headers. Otherwise, the request
	// will be rejected.
	// Note that Websocket allows secondary protocol negotiation which may then
	// be subject to further routing rules based on the protocol selected.
	WebsocketUpgrade bool `protobuf:"varint,5,opt,name=websocket_upgrade,json=websocketUpgrade" json:"websocket_upgrade,omitempty"`
	// Timeout for HTTP requests.
	Timeout *google_protobuf.Duration `protobuf:"bytes,6,opt,name=timeout" json:"timeout,omitempty"`
	// Retry policy for HTTP requests.
	Retries *HTTPRetry `protobuf:"bytes,7,opt,name=retries" json:"retries,omitempty"`
	// Fault injection policy to apply on HTTP traffic
	Fault *HTTPFaultInjection `protobuf:"bytes,8,opt,name=fault" json:"fault,omitempty"`
	// Mirror HTTP traffic to a another destination in addition to forwarding
	// the requests to the intended destination. Mirrored traffic is on a best
	// effort basis where Envoy will not wait for the mirrored cluster to
	// respond before returning the response from the original destination.
	// Statistics will be generated for the mirrored destination.
	Mirror *Destination `protobuf:"bytes,9,opt,name=mirror" json:"mirror,omitempty"`
	// Cross-Origin Resource Sharing policy (CORS). Refer to
	// https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS for
	// further details about cross origin resource sharing.
	CorsPolicy *CorsPolicy `protobuf:"bytes,10,opt,name=cors_policy,json=corsPolicy" json:"cors_policy,omitempty"`
	// Additional HTTP headers to add before forwarding a request to the
	// destnation service.
	AppendHeaders map[string]string `protobuf:"bytes,11,rep,name=append_headers,json=appendHeaders" json:"append_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *HTTPRoute) Reset()                    { *m = HTTPRoute{} }
func (m *HTTPRoute) String() string            { return proto.CompactTextString(m) }
func (*HTTPRoute) ProtoMessage()               {}
func (*HTTPRoute) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *HTTPRoute) GetMatch() []*HTTPMatchRequest {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *HTTPRoute) GetRoute() []*DestinationWeight {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *HTTPRoute) GetRedirect() *HTTPRedirect {
	if m != nil {
		return m.Redirect
	}
	return nil
}

func (m *HTTPRoute) GetRewrite() *HTTPRewrite {
	if m != nil {
		return m.Rewrite
	}
	return nil
}

func (m *HTTPRoute) GetWebsocketUpgrade() bool {
	if m != nil {
		return m.WebsocketUpgrade
	}
	return false
}

func (m *HTTPRoute) GetTimeout() *google_protobuf.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *HTTPRoute) GetRetries() *HTTPRetry {
	if m != nil {
		return m.Retries
	}
	return nil
}

func (m *HTTPRoute) GetFault() *HTTPFaultInjection {
	if m != nil {
		return m.Fault
	}
	return nil
}

func (m *HTTPRoute) GetMirror() *Destination {
	if m != nil {
		return m.Mirror
	}
	return nil
}

func (m *HTTPRoute) GetCorsPolicy() *CorsPolicy {
	if m != nil {
		return m.CorsPolicy
	}
	return nil
}

func (m *HTTPRoute) GetAppendHeaders() map[string]string {
	if m != nil {
		return m.AppendHeaders
	}
	return nil
}

// Describes match conditions and actions for routing TCP traffic.
// The following routing rule forwards traffic arriving at
// port 2379 named redis from 172.17.16.* subnet to another redis server on
// port 5555.
//
//     apiVersion: config.istio.io/v1alpha2
//     kind: RouteRule
//     metadata:
//       name: bookinfo-redis
//     spec:
//       hosts:
//         - myredissrv
//       tcp:
//         - match:
//             sourceSubnets:
//               - "172.17.16.0/24"
//             destinationPorts:
//               - redis #only applies to ports named redis
//           route:
//           - destination:
//               name: redis.prod
//
type TCPRoute struct {
	// Match conditions to be satisfied for the route rule to be
	// activated. All conditions inside a single match block have AND semantics,
	// while the list of match blocks have OR semantics. The rule is matched if
	// any one of the match blocks succeed.
	Match []*L4MatchAttributes `protobuf:"bytes,1,rep,name=match" json:"match,omitempty"`
	Route []*DestinationWeight `protobuf:"bytes,2,rep,name=route" json:"route,omitempty"`
}

func (m *TCPRoute) Reset()                    { *m = TCPRoute{} }
func (m *TCPRoute) String() string            { return proto.CompactTextString(m) }
func (*TCPRoute) ProtoMessage()               {}
func (*TCPRoute) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *TCPRoute) GetMatch() []*L4MatchAttributes {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *TCPRoute) GetRoute() []*DestinationWeight {
	if m != nil {
		return m.Route
	}
	return nil
}

// HttpMatchRequest specifies a set of criterion to be met in order for the
// route rule to be applied to the HTTP request. For example, the following
// route rule restricts the rule to match only requests where the URL path
// starts with /ratings/v2/ and the request contains a "cookie" with value
// "user=jason",
//
//     metadata:
//       name: my-rule
//       namespace: default
//     spec:
//       hosts:
//         - ratings
//       http:
//         - match:
//             - headers:
//                 cookie:
//                   regex: "^(.*?;)?(user=jason)(;.*)?"
//               uri:
//                 prefix: "/ratings/v2/"
//
// MatchCondition CANNOT be empty.
type HTTPMatchRequest struct {
	// URI to match
	// values are case-sensitive and formatted as follows:
	//
	// *exact: "value"* or just *"value"* for exact string match
	//
	// *prefix: "value"* for prefix-based match
	//
	// *regex: "value"* for ECMAscript style regex-based match
	//
	Uri *StringMatch `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	// URI Scheme
	// values are case-sensitive and formatted as follows:
	//
	// *exact: "value"* or just *"value"* for exact string match
	//
	// *prefix: "value"* for prefix-based match
	//
	// *regex: "value"* for ECMAscript style regex-based match
	//
	Scheme *StringMatch `protobuf:"bytes,2,opt,name=scheme" json:"scheme,omitempty"`
	// HTTP Method
	// values are case-sensitive and formatted as follows:
	//
	// *exact: "value"* or just *"value"* for exact string match
	//
	// *prefix: "value"* for prefix-based match
	//
	// *regex: "value"* for ECMAscript style regex-based match
	//
	Method *StringMatch `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	// HTTP Authority
	// values are case-sensitive and formatted as follows:
	//
	// *exact: "value"* or just *"value"* for exact string match
	//
	// *prefix: "value"* for prefix-based match
	//
	// *regex: "value"* for ECMAscript style regex-based match
	//
	Authority *StringMatch `protobuf:"bytes,4,opt,name=authority" json:"authority,omitempty"`
	// The header keys must be lowercase and use hyphen as the separator,
	// e.g. _x-request-id_.
	//
	// Header values are case-sensitive and formatted as follows:
	//
	// *exact: "value"* or just *"value"* for exact string match
	//
	// *prefix: "value"* for prefix-based match
	//
	// *regex: "value"* for ECMAscript style regex-based match
	//
	// *Note:* The keys _uri_, _scheme_, _method_, and _authority_ will be ignored.
	Headers map[string]*StringMatch `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Specifies the ports on the host that is being addressed. Many services
	// only expose a single port or label ports with the protocols they support,
	// in these cases it is not required to explicitly select the port. Note that
	// selection priority is to first match by name and then match by number.
	//
	// Names must comply with DNS label syntax (rfc1035) and therefore cannot
	// collide with numbers. If there are multiple ports on a service with the
	// same protocol the names should be of the form <protocol-name>-<DNS label>
	DestinationPorts []string `protobuf:"bytes,6,rep,name=destination_ports,json=destinationPorts" json:"destination_ports,omitempty"`
}

func (m *HTTPMatchRequest) Reset()                    { *m = HTTPMatchRequest{} }
func (m *HTTPMatchRequest) String() string            { return proto.CompactTextString(m) }
func (*HTTPMatchRequest) ProtoMessage()               {}
func (*HTTPMatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *HTTPMatchRequest) GetUri() *StringMatch {
	if m != nil {
		return m.Uri
	}
	return nil
}

func (m *HTTPMatchRequest) GetScheme() *StringMatch {
	if m != nil {
		return m.Scheme
	}
	return nil
}

func (m *HTTPMatchRequest) GetMethod() *StringMatch {
	if m != nil {
		return m.Method
	}
	return nil
}

func (m *HTTPMatchRequest) GetAuthority() *StringMatch {
	if m != nil {
		return m.Authority
	}
	return nil
}

func (m *HTTPMatchRequest) GetHeaders() map[string]*StringMatch {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HTTPMatchRequest) GetDestinationPorts() []string {
	if m != nil {
		return m.DestinationPorts
	}
	return nil
}

// Each routing rule is associated with one or more service versions (see
// glossary in beginning of document). Weights associated with the version
// determine the proportion of traffic it receives. For example, the
// following rule will route 25% of traffic for the "reviews" service to
// instances with the "v2" tag and the remaining traffic (i.e., 75%) to
// "v1".
//
//     metadata:
//       name: my-rule
//       namespace: default
//     spec:
//       hosts:
//         - reviews
//       http:
//         - route:
//           - destination:
//               labels:
//                 version: v2
//             weight: 25
//           - destination:
//               labels:
//                 version: v1
//             weight: 75
//
type DestinationWeight struct {
	// REQUIRED. Sometimes required. Optional destination uniquely identifies
	// the destination service. If not specified, the value is inherited from
	// the parent route rule.
	Destination *Destination `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	// REQUIRED. The proportion of traffic to be forwarded to the service
	// version. (0-100). Sum of weights across destinations SHOULD BE ==
	// 100. If there is only destination in a rule, the weight value is
	// assumed to be 100. When using multiple weights, either destination or labels must be
	// specified.
	Weight int32 `protobuf:"varint,2,opt,name=weight" json:"weight,omitempty"`
}

func (m *DestinationWeight) Reset()                    { *m = DestinationWeight{} }
func (m *DestinationWeight) String() string            { return proto.CompactTextString(m) }
func (*DestinationWeight) ProtoMessage()               {}
func (*DestinationWeight) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *DestinationWeight) GetDestination() *Destination {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *DestinationWeight) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

// L4 connection match attributes. Note that L4 connection matching support
// is incomplete.
type L4MatchAttributes struct {
	// IPv4 or IPv6 ip address with optional subnet. E.g., a.b.c.d/xx form or
	// just a.b.c.d
	SourceSubnets []string `protobuf:"bytes,1,rep,name=source_subnets,json=sourceSubnets" json:"source_subnets,omitempty"`
	// IPv4 or IPv6 ip address of destination with optional subnet.
	// E.g., a.b.c.d/xx form or just a.b.c.d. This is only valid when the destination
	// service has several IPs and the application explicitly specifies a particular IP.
	DestinationSubnets []string `protobuf:"bytes,2,rep,name=destination_subnets,json=destinationSubnets" json:"destination_subnets,omitempty"`
	// Specifies the ports on the host that is being addressed. Many services
	// only expose a single port or label ports with the protocols they support,
	// in these cases it is not required to explicitly select the port. Note that
	// selection priority is to first match by name and then match by number.
	//
	// Names must comply with DNS label syntax (rfc1035) and therefore cannot
	// collide with numbers. If there are multiple ports on a service with the
	// same protocol the names should be of the form <protocol-name>-<DNS label>
	DestinationPorts []string `protobuf:"bytes,3,rep,name=destination_ports,json=destinationPorts" json:"destination_ports,omitempty"`
}

func (m *L4MatchAttributes) Reset()                    { *m = L4MatchAttributes{} }
func (m *L4MatchAttributes) String() string            { return proto.CompactTextString(m) }
func (*L4MatchAttributes) ProtoMessage()               {}
func (*L4MatchAttributes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *L4MatchAttributes) GetSourceSubnets() []string {
	if m != nil {
		return m.SourceSubnets
	}
	return nil
}

func (m *L4MatchAttributes) GetDestinationSubnets() []string {
	if m != nil {
		return m.DestinationSubnets
	}
	return nil
}

func (m *L4MatchAttributes) GetDestinationPorts() []string {
	if m != nil {
		return m.DestinationPorts
	}
	return nil
}

// HTTPRedirect can be used to send a 302 redirect response to the caller,
// where the Authority/Host and the URI in the response can be swapped with
// the specified values. For example, the following route rule redirects
// requests for /v1/getProductRatings API on the ratings service to
// /v1/bookRatings provided by the bookratings service.
//
//     metadata:
//       name: my-rule
//       namespace: default
//     spec:
//       hosts:
//         - ratings
//       http:
//         - match:
//           - uri:
//               exact: /v1/getProductRatings
//           redirect:
//             uri: /v1/bookRatings
//             authority: bookratings.default.svc.cluster.local
//
type HTTPRedirect struct {
	// On a redirect, overwrite the Path portion of the URL with this
	// value. Note that the entire path will be replaced, irrespective of the
	// request URI being matched as an exact path or prefix.
	Uri string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	// On a redirect, overwrite the Authority/Host portion of the URL with
	// this value
	Authority string `protobuf:"bytes,2,opt,name=authority" json:"authority,omitempty"`
}

func (m *HTTPRedirect) Reset()                    { *m = HTTPRedirect{} }
func (m *HTTPRedirect) String() string            { return proto.CompactTextString(m) }
func (*HTTPRedirect) ProtoMessage()               {}
func (*HTTPRedirect) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *HTTPRedirect) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *HTTPRedirect) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

// HTTPRewrite can be used to rewrite specific parts of a HTTP request
// before forwarding the request to the destination. Rewrite primitive can
// be used only with the DestinationWeights. The following example
// demonstrates how to rewrite the URL prefix for api call (/ratings) to
// ratings service before making the actual API call.
//
//     metadata:
//       name: my-rule
//       namespace: default
//     spec:
//       hosts:
//         - ratings
//       http:
//         - match:
//           - uri:
//               prefix: /ratings
//           rewrite:
//             uri: /v1/bookRatings
//           route:
//           - destination:
//               labels:
//                 version: v1
//
type HTTPRewrite struct {
	// rewrite the Path (or the prefix) portion of the URI with this
	// value. If the original URI was matched based on prefix, the value
	// provided in this field will replace the corresponding matched prefix.
	Uri string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	// rewrite the Authority/Host header with this value.
	Authority string `protobuf:"bytes,2,opt,name=authority" json:"authority,omitempty"`
}

func (m *HTTPRewrite) Reset()                    { *m = HTTPRewrite{} }
func (m *HTTPRewrite) String() string            { return proto.CompactTextString(m) }
func (*HTTPRewrite) ProtoMessage()               {}
func (*HTTPRewrite) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *HTTPRewrite) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *HTTPRewrite) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

// Describes how to match a given string in HTTP headers. Match is case-sensitive.
type StringMatch struct {
	// Types that are valid to be assigned to MatchType:
	//	*StringMatch_Exact
	//	*StringMatch_Prefix
	//	*StringMatch_Regex
	MatchType isStringMatch_MatchType `protobuf_oneof:"match_type"`
}

func (m *StringMatch) Reset()                    { *m = StringMatch{} }
func (m *StringMatch) String() string            { return proto.CompactTextString(m) }
func (*StringMatch) ProtoMessage()               {}
func (*StringMatch) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type isStringMatch_MatchType interface {
	isStringMatch_MatchType()
}

type StringMatch_Exact struct {
	Exact string `protobuf:"bytes,1,opt,name=exact,oneof"`
}
type StringMatch_Prefix struct {
	Prefix string `protobuf:"bytes,2,opt,name=prefix,oneof"`
}
type StringMatch_Regex struct {
	Regex string `protobuf:"bytes,3,opt,name=regex,oneof"`
}

func (*StringMatch_Exact) isStringMatch_MatchType()  {}
func (*StringMatch_Prefix) isStringMatch_MatchType() {}
func (*StringMatch_Regex) isStringMatch_MatchType()  {}

func (m *StringMatch) GetMatchType() isStringMatch_MatchType {
	if m != nil {
		return m.MatchType
	}
	return nil
}

func (m *StringMatch) GetExact() string {
	if x, ok := m.GetMatchType().(*StringMatch_Exact); ok {
		return x.Exact
	}
	return ""
}

func (m *StringMatch) GetPrefix() string {
	if x, ok := m.GetMatchType().(*StringMatch_Prefix); ok {
		return x.Prefix
	}
	return ""
}

func (m *StringMatch) GetRegex() string {
	if x, ok := m.GetMatchType().(*StringMatch_Regex); ok {
		return x.Regex
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StringMatch) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StringMatch_OneofMarshaler, _StringMatch_OneofUnmarshaler, _StringMatch_OneofSizer, []interface{}{
		(*StringMatch_Exact)(nil),
		(*StringMatch_Prefix)(nil),
		(*StringMatch_Regex)(nil),
	}
}

func _StringMatch_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StringMatch)
	// match_type
	switch x := m.MatchType.(type) {
	case *StringMatch_Exact:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Exact)
	case *StringMatch_Prefix:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Prefix)
	case *StringMatch_Regex:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Regex)
	case nil:
	default:
		return fmt.Errorf("StringMatch.MatchType has unexpected type %T", x)
	}
	return nil
}

func _StringMatch_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StringMatch)
	switch tag {
	case 1: // match_type.exact
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.MatchType = &StringMatch_Exact{x}
		return true, err
	case 2: // match_type.prefix
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.MatchType = &StringMatch_Prefix{x}
		return true, err
	case 3: // match_type.regex
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.MatchType = &StringMatch_Regex{x}
		return true, err
	default:
		return false, nil
	}
}

func _StringMatch_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StringMatch)
	// match_type
	switch x := m.MatchType.(type) {
	case *StringMatch_Exact:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Exact)))
		n += len(x.Exact)
	case *StringMatch_Prefix:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Prefix)))
		n += len(x.Prefix)
	case *StringMatch_Regex:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Regex)))
		n += len(x.Regex)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Describes the retry policy to use when a HTTP request fails. For
// example, the following rule sets the maximum number of retries to 3 when
// calling ratings:v1 service, with a 2s timeout per retry attempt.
//
//     metadata:
//       name: my-rule
//       namespace: default
//     spec:
//       hosts:
//         - ratings
//       http:
//         - route:
//           - destination:
//               labels:
//                  version: v1
//           retries:
//             attempts: 3
//             perTryTimeout: 2s
//
type HTTPRetry struct {
	// REQUIRED. Number of retries for a given request. The interval
	// between retries will be determined automatically (25ms+). Actual
	// number of retries attempted depends on the httpReqTimeout.
	Attempts int32 `protobuf:"varint,1,opt,name=attempts" json:"attempts,omitempty"`
	// Timeout per retry attempt for a given request. format: 1h/1m/1s/1ms. MUST BE >=1ms.
	PerTryTimeout *google_protobuf.Duration `protobuf:"bytes,2,opt,name=per_try_timeout,json=perTryTimeout" json:"per_try_timeout,omitempty"`
}

func (m *HTTPRetry) Reset()                    { *m = HTTPRetry{} }
func (m *HTTPRetry) String() string            { return proto.CompactTextString(m) }
func (*HTTPRetry) ProtoMessage()               {}
func (*HTTPRetry) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *HTTPRetry) GetAttempts() int32 {
	if m != nil {
		return m.Attempts
	}
	return 0
}

func (m *HTTPRetry) GetPerTryTimeout() *google_protobuf.Duration {
	if m != nil {
		return m.PerTryTimeout
	}
	return nil
}

// Describes the Cross-Origin Resource Sharing (CORS) policy, for a given
// service. Refer to
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
// for further details about cross origin resource sharing. For example,
// the following rule restricts cross origin requests to those originating
// from example.com domain using HTTP POST/GET, and sets the
// Access-Control-Allow-Credentials header to false. In addition, it only exposes
// X-Foo-bar header and sets an expiry period of 1 day.
//
//     metadata:
//       name: my-rule
//       namespace: default
//     spec:
//       hosts:
//         - ratings
//       http:
//         - route:
//           - destination:
//               labels:
//                 version: v1
//           corsPolicy:
//             allowOrigin:
//             - example.com
//             allowMethods:
//             - POST
//             - GET
//             allowCredentials: false
//             allowHeaders:
//             - X-Foo-Bar
//             maxAge: "1d"
//
type CorsPolicy struct {
	// The list of origins that are allowed to perform CORS requests. The content will
	// be serialized into the Access-Control-Allow-Origin header. Wildcard * will allow
	// all origins.
	AllowOrigin []string `protobuf:"bytes,1,rep,name=allow_origin,json=allowOrigin" json:"allow_origin,omitempty"`
	// List of HTTP methods allowed to access the resource. The content will
	// be serialized into the Access-Control-Allow-Methods header.
	AllowMethods []string `protobuf:"bytes,2,rep,name=allow_methods,json=allowMethods" json:"allow_methods,omitempty"`
	// List of HTTP headers that can be used when requesting the
	// resource. Serialized to Access-Control-Allow-Methods header.
	AllowHeaders []string `protobuf:"bytes,3,rep,name=allow_headers,json=allowHeaders" json:"allow_headers,omitempty"`
	// A white list of HTTP headers that the browsers are allowed to
	// access. Serialized into Access-Control-Expose-Headers header.
	ExposeHeaders []string `protobuf:"bytes,4,rep,name=expose_headers,json=exposeHeaders" json:"expose_headers,omitempty"`
	// Specifies how long the the results of a preflight request can be
	// cached. Translates to the Access-Control-Max-Age header.
	MaxAge *google_protobuf.Duration `protobuf:"bytes,5,opt,name=max_age,json=maxAge" json:"max_age,omitempty"`
	// Indicates whether the caller is allowed to send the actual request
	// (not the preflight) using credentials. Translates to
	// Access-Control-Allow-Credentials header.
	AllowCredentials *google_protobuf1.BoolValue `protobuf:"bytes,6,opt,name=allow_credentials,json=allowCredentials" json:"allow_credentials,omitempty"`
}

func (m *CorsPolicy) Reset()                    { *m = CorsPolicy{} }
func (m *CorsPolicy) String() string            { return proto.CompactTextString(m) }
func (*CorsPolicy) ProtoMessage()               {}
func (*CorsPolicy) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *CorsPolicy) GetAllowOrigin() []string {
	if m != nil {
		return m.AllowOrigin
	}
	return nil
}

func (m *CorsPolicy) GetAllowMethods() []string {
	if m != nil {
		return m.AllowMethods
	}
	return nil
}

func (m *CorsPolicy) GetAllowHeaders() []string {
	if m != nil {
		return m.AllowHeaders
	}
	return nil
}

func (m *CorsPolicy) GetExposeHeaders() []string {
	if m != nil {
		return m.ExposeHeaders
	}
	return nil
}

func (m *CorsPolicy) GetMaxAge() *google_protobuf.Duration {
	if m != nil {
		return m.MaxAge
	}
	return nil
}

func (m *CorsPolicy) GetAllowCredentials() *google_protobuf1.BoolValue {
	if m != nil {
		return m.AllowCredentials
	}
	return nil
}

// HTTPFaultInjection can be used to specify one or more faults to inject
// while forwarding http requests to the destination specified in the route
// rule.  Fault specification is part of a route rule. Faults include
// aborting the Http request from downstream service, and/or delaying
// proxying of requests. A fault rule MUST HAVE delay or abort or both.
//
// *Note:* Delay and abort faults are independent of one another, even if
// both are specified simultaneously.
type HTTPFaultInjection struct {
	// Delay requests before forwarding, emulating various failures such as
	// network issues, overloaded upstream service, etc.
	Delay *HTTPFaultInjection_Delay `protobuf:"bytes,1,opt,name=delay" json:"delay,omitempty"`
	// Abort Http request attempts and return error codes back to downstream
	// service, giving the impression that the upstream service is faulty.
	Abort *HTTPFaultInjection_Abort `protobuf:"bytes,2,opt,name=abort" json:"abort,omitempty"`
}

func (m *HTTPFaultInjection) Reset()                    { *m = HTTPFaultInjection{} }
func (m *HTTPFaultInjection) String() string            { return proto.CompactTextString(m) }
func (*HTTPFaultInjection) ProtoMessage()               {}
func (*HTTPFaultInjection) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *HTTPFaultInjection) GetDelay() *HTTPFaultInjection_Delay {
	if m != nil {
		return m.Delay
	}
	return nil
}

func (m *HTTPFaultInjection) GetAbort() *HTTPFaultInjection_Abort {
	if m != nil {
		return m.Abort
	}
	return nil
}

// Delay specification is used to inject latency into the request
// forwarding path. The following example will introduce a 5 second delay
// in 10% of the requests to the "v1" version of the "reviews"
// service.
//
//     metadata:
//       name: my-rule
//     spec:
//       hosts:
//         - reviews
//       http:
//         - route:
//           - destination:
//               labels:
//                 version: v1
//           fault:
//             delay:
//               percent: 10
//               fixedDelay: 5s
//
// The _fixedDelay_ field is used to indicate the amount of delay in
// seconds. An optional _percent_ field, a value between 0 and 100, can
// be used to only delay a certain percentage of requests. If left
// unspecified, all request will be delayed.
type HTTPFaultInjection_Delay struct {
	// percentage of requests on which the delay will be injected (0-100)
	Percent int32 `protobuf:"varint,1,opt,name=percent" json:"percent,omitempty"`
	// Types that are valid to be assigned to HttpDelayType:
	//	*HTTPFaultInjection_Delay_FixedDelay
	//	*HTTPFaultInjection_Delay_ExponentialDelay
	HttpDelayType isHTTPFaultInjection_Delay_HttpDelayType `protobuf_oneof:"http_delay_type"`
}

func (m *HTTPFaultInjection_Delay) Reset()                    { *m = HTTPFaultInjection_Delay{} }
func (m *HTTPFaultInjection_Delay) String() string            { return proto.CompactTextString(m) }
func (*HTTPFaultInjection_Delay) ProtoMessage()               {}
func (*HTTPFaultInjection_Delay) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13, 0} }

type isHTTPFaultInjection_Delay_HttpDelayType interface {
	isHTTPFaultInjection_Delay_HttpDelayType()
}

type HTTPFaultInjection_Delay_FixedDelay struct {
	FixedDelay *google_protobuf.Duration `protobuf:"bytes,2,opt,name=fixed_delay,json=fixedDelay,oneof"`
}
type HTTPFaultInjection_Delay_ExponentialDelay struct {
	ExponentialDelay *google_protobuf.Duration `protobuf:"bytes,3,opt,name=exponential_delay,json=exponentialDelay,oneof"`
}

func (*HTTPFaultInjection_Delay_FixedDelay) isHTTPFaultInjection_Delay_HttpDelayType()       {}
func (*HTTPFaultInjection_Delay_ExponentialDelay) isHTTPFaultInjection_Delay_HttpDelayType() {}

func (m *HTTPFaultInjection_Delay) GetHttpDelayType() isHTTPFaultInjection_Delay_HttpDelayType {
	if m != nil {
		return m.HttpDelayType
	}
	return nil
}

func (m *HTTPFaultInjection_Delay) GetPercent() int32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *HTTPFaultInjection_Delay) GetFixedDelay() *google_protobuf.Duration {
	if x, ok := m.GetHttpDelayType().(*HTTPFaultInjection_Delay_FixedDelay); ok {
		return x.FixedDelay
	}
	return nil
}

func (m *HTTPFaultInjection_Delay) GetExponentialDelay() *google_protobuf.Duration {
	if x, ok := m.GetHttpDelayType().(*HTTPFaultInjection_Delay_ExponentialDelay); ok {
		return x.ExponentialDelay
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*HTTPFaultInjection_Delay) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _HTTPFaultInjection_Delay_OneofMarshaler, _HTTPFaultInjection_Delay_OneofUnmarshaler, _HTTPFaultInjection_Delay_OneofSizer, []interface{}{
		(*HTTPFaultInjection_Delay_FixedDelay)(nil),
		(*HTTPFaultInjection_Delay_ExponentialDelay)(nil),
	}
}

func _HTTPFaultInjection_Delay_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*HTTPFaultInjection_Delay)
	// http_delay_type
	switch x := m.HttpDelayType.(type) {
	case *HTTPFaultInjection_Delay_FixedDelay:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FixedDelay); err != nil {
			return err
		}
	case *HTTPFaultInjection_Delay_ExponentialDelay:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExponentialDelay); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("HTTPFaultInjection_Delay.HttpDelayType has unexpected type %T", x)
	}
	return nil
}

func _HTTPFaultInjection_Delay_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*HTTPFaultInjection_Delay)
	switch tag {
	case 2: // http_delay_type.fixed_delay
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf.Duration)
		err := b.DecodeMessage(msg)
		m.HttpDelayType = &HTTPFaultInjection_Delay_FixedDelay{msg}
		return true, err
	case 3: // http_delay_type.exponential_delay
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf.Duration)
		err := b.DecodeMessage(msg)
		m.HttpDelayType = &HTTPFaultInjection_Delay_ExponentialDelay{msg}
		return true, err
	default:
		return false, nil
	}
}

func _HTTPFaultInjection_Delay_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*HTTPFaultInjection_Delay)
	// http_delay_type
	switch x := m.HttpDelayType.(type) {
	case *HTTPFaultInjection_Delay_FixedDelay:
		s := proto.Size(x.FixedDelay)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *HTTPFaultInjection_Delay_ExponentialDelay:
		s := proto.Size(x.ExponentialDelay)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Abort specification is used to prematurely abort a request with a
// pre-specified error code. The following example will return an HTTP
// 400 error code for 10% of the requests to the "ratings" service "v1".
//
//     metadata:
//       name: my-rule
//     spec:
//       hosts:
//         - reviews
//       http:
//         - route:
//           - destination:
//               labels:
//                 version: v1
//           fault:
//             abort:
//               percent: 10
//               httpStatus: 400
//
// The _httpStatus_ field is used to indicate the HTTP status code to
// return to the caller. The optional _percent_ field, a value between 0
// and 100, is used to only abort a certain percentage of requests. If
// not specified, all requests are aborted.
type HTTPFaultInjection_Abort struct {
	// percentage of requests to be aborted with the error code provided (0-100).
	Percent int32 `protobuf:"varint,1,opt,name=percent" json:"percent,omitempty"`
	// Types that are valid to be assigned to ErrorType:
	//	*HTTPFaultInjection_Abort_GrpcStatus
	//	*HTTPFaultInjection_Abort_Http2Error
	//	*HTTPFaultInjection_Abort_HttpStatus
	ErrorType isHTTPFaultInjection_Abort_ErrorType `protobuf_oneof:"error_type"`
}

func (m *HTTPFaultInjection_Abort) Reset()                    { *m = HTTPFaultInjection_Abort{} }
func (m *HTTPFaultInjection_Abort) String() string            { return proto.CompactTextString(m) }
func (*HTTPFaultInjection_Abort) ProtoMessage()               {}
func (*HTTPFaultInjection_Abort) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13, 1} }

type isHTTPFaultInjection_Abort_ErrorType interface {
	isHTTPFaultInjection_Abort_ErrorType()
}

type HTTPFaultInjection_Abort_GrpcStatus struct {
	GrpcStatus string `protobuf:"bytes,2,opt,name=grpc_status,json=grpcStatus,oneof"`
}
type HTTPFaultInjection_Abort_Http2Error struct {
	Http2Error string `protobuf:"bytes,3,opt,name=http2_error,json=http2Error,oneof"`
}
type HTTPFaultInjection_Abort_HttpStatus struct {
	HttpStatus int32 `protobuf:"varint,4,opt,name=http_status,json=httpStatus,oneof"`
}

func (*HTTPFaultInjection_Abort_GrpcStatus) isHTTPFaultInjection_Abort_ErrorType() {}
func (*HTTPFaultInjection_Abort_Http2Error) isHTTPFaultInjection_Abort_ErrorType() {}
func (*HTTPFaultInjection_Abort_HttpStatus) isHTTPFaultInjection_Abort_ErrorType() {}

func (m *HTTPFaultInjection_Abort) GetErrorType() isHTTPFaultInjection_Abort_ErrorType {
	if m != nil {
		return m.ErrorType
	}
	return nil
}

func (m *HTTPFaultInjection_Abort) GetPercent() int32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *HTTPFaultInjection_Abort) GetGrpcStatus() string {
	if x, ok := m.GetErrorType().(*HTTPFaultInjection_Abort_GrpcStatus); ok {
		return x.GrpcStatus
	}
	return ""
}

func (m *HTTPFaultInjection_Abort) GetHttp2Error() string {
	if x, ok := m.GetErrorType().(*HTTPFaultInjection_Abort_Http2Error); ok {
		return x.Http2Error
	}
	return ""
}

func (m *HTTPFaultInjection_Abort) GetHttpStatus() int32 {
	if x, ok := m.GetErrorType().(*HTTPFaultInjection_Abort_HttpStatus); ok {
		return x.HttpStatus
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*HTTPFaultInjection_Abort) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _HTTPFaultInjection_Abort_OneofMarshaler, _HTTPFaultInjection_Abort_OneofUnmarshaler, _HTTPFaultInjection_Abort_OneofSizer, []interface{}{
		(*HTTPFaultInjection_Abort_GrpcStatus)(nil),
		(*HTTPFaultInjection_Abort_Http2Error)(nil),
		(*HTTPFaultInjection_Abort_HttpStatus)(nil),
	}
}

func _HTTPFaultInjection_Abort_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*HTTPFaultInjection_Abort)
	// error_type
	switch x := m.ErrorType.(type) {
	case *HTTPFaultInjection_Abort_GrpcStatus:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.GrpcStatus)
	case *HTTPFaultInjection_Abort_Http2Error:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Http2Error)
	case *HTTPFaultInjection_Abort_HttpStatus:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.HttpStatus))
	case nil:
	default:
		return fmt.Errorf("HTTPFaultInjection_Abort.ErrorType has unexpected type %T", x)
	}
	return nil
}

func _HTTPFaultInjection_Abort_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*HTTPFaultInjection_Abort)
	switch tag {
	case 2: // error_type.grpc_status
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.ErrorType = &HTTPFaultInjection_Abort_GrpcStatus{x}
		return true, err
	case 3: // error_type.http2_error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.ErrorType = &HTTPFaultInjection_Abort_Http2Error{x}
		return true, err
	case 4: // error_type.http_status
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.ErrorType = &HTTPFaultInjection_Abort_HttpStatus{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _HTTPFaultInjection_Abort_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*HTTPFaultInjection_Abort)
	// error_type
	switch x := m.ErrorType.(type) {
	case *HTTPFaultInjection_Abort_GrpcStatus:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.GrpcStatus)))
		n += len(x.GrpcStatus)
	case *HTTPFaultInjection_Abort_Http2Error:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Http2Error)))
		n += len(x.Http2Error)
	case *HTTPFaultInjection_Abort_HttpStatus:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.HttpStatus))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*RouteRule)(nil), "istio.routing.v1alpha2.RouteRule")
	proto.RegisterType((*Destination)(nil), "istio.routing.v1alpha2.Destination")
	proto.RegisterType((*Source)(nil), "istio.routing.v1alpha2.Source")
	proto.RegisterType((*HTTPRoute)(nil), "istio.routing.v1alpha2.HTTPRoute")
	proto.RegisterType((*TCPRoute)(nil), "istio.routing.v1alpha2.TCPRoute")
	proto.RegisterType((*HTTPMatchRequest)(nil), "istio.routing.v1alpha2.HTTPMatchRequest")
	proto.RegisterType((*DestinationWeight)(nil), "istio.routing.v1alpha2.DestinationWeight")
	proto.RegisterType((*L4MatchAttributes)(nil), "istio.routing.v1alpha2.L4MatchAttributes")
	proto.RegisterType((*HTTPRedirect)(nil), "istio.routing.v1alpha2.HTTPRedirect")
	proto.RegisterType((*HTTPRewrite)(nil), "istio.routing.v1alpha2.HTTPRewrite")
	proto.RegisterType((*StringMatch)(nil), "istio.routing.v1alpha2.StringMatch")
	proto.RegisterType((*HTTPRetry)(nil), "istio.routing.v1alpha2.HTTPRetry")
	proto.RegisterType((*CorsPolicy)(nil), "istio.routing.v1alpha2.CorsPolicy")
	proto.RegisterType((*HTTPFaultInjection)(nil), "istio.routing.v1alpha2.HTTPFaultInjection")
	proto.RegisterType((*HTTPFaultInjection_Delay)(nil), "istio.routing.v1alpha2.HTTPFaultInjection.Delay")
	proto.RegisterType((*HTTPFaultInjection_Abort)(nil), "istio.routing.v1alpha2.HTTPFaultInjection.Abort")
}

func init() { proto.RegisterFile("routing/v1alpha2/route_rule.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xdb, 0x46,
	0x13, 0x0d, 0x45, 0x53, 0xb2, 0x86, 0x76, 0x62, 0xef, 0xf7, 0x21, 0x60, 0x85, 0x22, 0xb0, 0x95,
	0x16, 0x70, 0x53, 0x80, 0x6e, 0x95, 0x04, 0x48, 0x9a, 0x26, 0x8d, 0xed, 0xfc, 0xb8, 0x40, 0x82,
	0x04, 0xb4, 0xdb, 0x5e, 0xf4, 0x82, 0x58, 0x51, 0x63, 0x8a, 0x09, 0x45, 0xb2, 0xcb, 0x65, 0x2c,
	0xbd, 0x43, 0x81, 0xde, 0x06, 0x28, 0xfa, 0x20, 0x05, 0xfa, 0x34, 0x05, 0xfa, 0x1a, 0x45, 0xb1,
	0xb3, 0xa4, 0xcc, 0x56, 0xb6, 0x24, 0xa3, 0xbd, 0xe3, 0x0e, 0xcf, 0x39, 0xdc, 0x9d, 0x99, 0xb3,
	0x43, 0xd8, 0x16, 0x69, 0x21, 0xa3, 0x24, 0xdc, 0x7d, 0xf7, 0x39, 0x8f, 0xb3, 0x21, 0xef, 0xed,
	0xaa, 0x00, 0xfa, 0xa2, 0x88, 0xd1, 0xcd, 0x44, 0x2a, 0x53, 0x76, 0x3d, 0xca, 0x65, 0x94, 0xba,
	0x25, 0xd0, 0xad, 0x80, 0x9d, 0x1b, 0x61, 0x9a, 0x86, 0x31, 0xee, 0x12, 0xaa, 0x5f, 0x9c, 0xec,
	0x0e, 0x0a, 0xc1, 0x65, 0x94, 0x26, 0x9a, 0x37, 0xfb, 0xfe, 0x54, 0xf0, 0x2c, 0x43, 0x91, 0xeb,
	0xf7, 0xdd, 0xdf, 0x0d, 0x68, 0x7b, 0xea, 0x63, 0x5e, 0x11, 0x23, 0xfb, 0x3f, 0x58, 0xc3, 0x34,
	0x97, 0xb9, 0x63, 0x6c, 0x99, 0x3b, 0x6d, 0x4f, 0x2f, 0xd8, 0x3d, 0x68, 0xe5, 0x69, 0x21, 0x02,
	0xcc, 0x9d, 0xc6, 0x96, 0xb9, 0x63, 0xf7, 0x6e, 0xb8, 0xe7, 0xef, 0xc6, 0x3d, 0x22, 0x98, 0x57,
	0xc1, 0x59, 0x07, 0x56, 0x43, 0x2e, 0xf1, 0x94, 0x4f, 0x72, 0xc7, 0x24, 0xc9, 0xe9, 0x9a, 0xdd,
	0x85, 0x95, 0xa1, 0x94, 0x99, 0xb3, 0x42, 0x92, 0xdb, 0x17, 0x49, 0x1e, 0x1e, 0x1f, 0xbf, 0xd6,
	0x1b, 0x24, 0x38, 0xeb, 0x81, 0x29, 0x83, 0xcc, 0xb1, 0x88, 0xb5, 0x75, 0x11, 0xeb, 0xf8, 0xa0,
	0x24, 0x29, 0x70, 0xf7, 0x57, 0x03, 0xec, 0x27, 0x98, 0xcb, 0x28, 0xa1, 0xd4, 0xb0, 0xe7, 0xd0,
	0x8c, 0x79, 0x1f, 0x63, 0x7d, 0x4e, 0xbb, 0xb7, 0x7b, 0x91, 0x4c, 0x8d, 0xe4, 0xbe, 0x20, 0xc6,
	0xd3, 0x44, 0x8a, 0x89, 0x57, 0xd2, 0x19, 0x83, 0x15, 0x95, 0x22, 0xa7, 0xb1, 0x65, 0xec, 0xb4,
	0x3d, 0x7a, 0x56, 0xb1, 0x2c, 0x15, 0xd2, 0xb1, 0x74, 0x4c, 0x3d, 0x77, 0xee, 0x83, 0x5d, 0xa3,
	0xb3, 0x0d, 0x30, 0xdf, 0xe2, 0xc4, 0x31, 0x08, 0xa1, 0x1e, 0x55, 0xe2, 0xdf, 0xf1, 0xb8, 0xc0,
	0x52, 0x49, 0x2f, 0xbe, 0x68, 0xdc, 0x33, 0xba, 0x3f, 0x1b, 0xd0, 0xd4, 0x69, 0x55, 0xca, 0x09,
	0x1f, 0x61, 0xc9, 0xa3, 0x67, 0xb6, 0x3f, 0x3d, 0x8a, 0x2e, 0xcd, 0xad, 0xf9, 0xa5, 0x39, 0xef,
	0x14, 0xff, 0x66, 0x77, 0x3f, 0x35, 0xa1, 0x3d, 0xad, 0x10, 0x7b, 0x04, 0xd6, 0x88, 0xcb, 0x60,
	0x58, 0xa6, 0x75, 0x67, 0x5e, 0x4d, 0x5f, 0x2a, 0xa0, 0x87, 0x3f, 0x14, 0x98, 0x4b, 0x4f, 0xd3,
	0xd8, 0x57, 0x60, 0x51, 0xe3, 0x97, 0x67, 0xf9, 0x64, 0x89, 0xb2, 0x7c, 0x87, 0x51, 0x38, 0x94,
	0x9e, 0xe6, 0xb1, 0xc7, 0xb0, 0x2a, 0x70, 0x10, 0x09, 0x0c, 0xa4, 0x63, 0x6e, 0x19, 0x3b, 0x76,
	0xef, 0xa3, 0xb9, 0x7d, 0x55, 0x62, 0xbd, 0x29, 0x8b, 0x3d, 0x84, 0x96, 0xc0, 0x53, 0x11, 0x49,
	0x74, 0x56, 0x48, 0xe0, 0xe6, 0x7c, 0x01, 0x82, 0x7a, 0x15, 0x87, 0x7d, 0x0a, 0x9b, 0xa7, 0xd8,
	0xcf, 0xd3, 0xe0, 0x2d, 0x4a, 0xbf, 0xc8, 0x42, 0xc1, 0x07, 0x48, 0x9d, 0xb0, 0xea, 0x6d, 0x4c,
	0x5f, 0x7c, 0xa3, 0xe3, 0xec, 0x36, 0xb4, 0x64, 0x34, 0xc2, 0xb4, 0x90, 0x4e, 0x93, 0xbe, 0xf5,
	0x81, 0xab, 0xdd, 0xea, 0x56, 0x6e, 0x75, 0x9f, 0x94, 0x6e, 0xf6, 0x2a, 0x24, 0x7b, 0xa0, 0x36,
	0x28, 0x45, 0x84, 0xb9, 0xd3, 0x22, 0xd2, 0x7c, 0xe7, 0xa0, 0x2a, 0x74, 0xc5, 0x60, 0x8f, 0xc1,
	0x3a, 0xe1, 0x45, 0x2c, 0x9d, 0x55, 0xa2, 0xde, 0x9a, 0x47, 0x7d, 0xa6, 0x80, 0x5f, 0x27, 0x6f,
	0x30, 0xa0, 0x0d, 0x68, 0x22, 0x7b, 0x00, 0xcd, 0x51, 0x24, 0x44, 0x2a, 0x9c, 0xf6, 0xfc, 0xf4,
	0xd4, 0x6a, 0xe4, 0x95, 0x14, 0x76, 0x00, 0x76, 0x90, 0x8a, 0xdc, 0xcf, 0xd2, 0x38, 0x0a, 0x26,
	0x0e, 0x90, 0x42, 0xf7, 0x22, 0x85, 0x83, 0x54, 0xe4, 0xaf, 0x09, 0xe9, 0x41, 0x30, 0x7d, 0x66,
	0xdf, 0xc3, 0x55, 0x75, 0x83, 0x25, 0x03, 0x7f, 0x88, 0x7c, 0x80, 0x22, 0x77, 0x6c, 0xea, 0x96,
	0x3b, 0x0b, 0x6f, 0x10, 0x77, 0x8f, 0x78, 0x87, 0x9a, 0xa6, 0x3d, 0xb0, 0xce, 0xeb, 0xb1, 0xce,
	0x63, 0x60, 0xb3, 0xa0, 0x4b, 0x39, 0xe2, 0x47, 0x03, 0x56, 0xab, 0xdb, 0x47, 0x35, 0x74, 0xdd,
	0x10, 0x17, 0x36, 0xf4, 0x8b, 0x3b, 0x64, 0x87, 0x3d, 0x29, 0x45, 0xd4, 0x2f, 0x24, 0xe6, 0xff,
	0x95, 0x23, 0xba, 0x7f, 0x98, 0xb0, 0xf1, 0x4f, 0xbb, 0xb1, 0xbb, 0x60, 0x16, 0x22, 0xa2, 0xf3,
	0xcc, 0xa9, 0xe0, 0x91, 0x14, 0x51, 0x12, 0x6a, 0xa2, 0xc2, 0xab, 0xda, 0xe7, 0xc1, 0x10, 0x47,
	0xfa, 0xd4, 0x4b, 0x32, 0x4b, 0x0a, 0x35, 0x0e, 0xca, 0x61, 0x3a, 0x28, 0x8d, 0xb9, 0x1c, 0x59,
	0x53, 0xd8, 0x1e, 0xb4, 0x79, 0x21, 0x87, 0xa9, 0x88, 0xe4, 0x64, 0x91, 0x2f, 0xeb, 0xfc, 0x33,
	0x16, 0x7b, 0x05, 0xad, 0xaa, 0x5f, 0xf4, 0xec, 0xb8, 0xbb, 0xec, 0xed, 0xe4, 0xfe, 0xad, 0x61,
	0x2a, 0x15, 0x65, 0xf5, 0xc1, 0x59, 0xd6, 0x7d, 0x75, 0xcf, 0xe7, 0x4e, 0x93, 0x86, 0xdc, 0x46,
	0xed, 0xc5, 0x6b, 0x15, 0xef, 0xf8, 0xb0, 0xb6, 0xa0, 0xa3, 0xee, 0xd7, 0x3b, 0x6a, 0xc9, 0xe3,
	0xd5, 0xda, 0x4e, 0xc0, 0xe6, 0x4c, 0x0f, 0xb0, 0xa7, 0x60, 0xd7, 0x76, 0xb2, 0xa8, 0xde, 0x75,
	0xc7, 0xd6, 0x79, 0xec, 0x3a, 0x34, 0x4f, 0x49, 0x90, 0xf6, 0x66, 0x79, 0xe5, 0xaa, 0xfb, 0xde,
	0x80, 0xcd, 0x99, 0xce, 0x65, 0x1f, 0xc3, 0x55, 0x3d, 0xfe, 0xfd, 0xbc, 0xe8, 0x27, 0x38, 0xfd,
	0x99, 0x58, 0xd7, 0xd1, 0x23, 0x1d, 0x64, 0xbb, 0xf0, 0xbf, 0x7a, 0xfa, 0x2a, 0x6c, 0x83, 0xb0,
	0xac, 0xf6, 0xaa, 0x22, 0x9c, 0x9b, 0x6f, 0xf3, 0xfc, 0x7c, 0x77, 0x1f, 0xc1, 0x5a, 0xfd, 0x82,
	0x57, 0xf9, 0xae, 0x3a, 0xbe, 0xad, 0x9b, 0xf9, 0xc3, 0x7a, 0x4b, 0x69, 0x17, 0x9f, 0x05, 0xba,
	0x0f, 0xc1, 0xae, 0xdd, 0xef, 0x97, 0xa6, 0x23, 0xd8, 0xb5, 0x3a, 0xb1, 0xeb, 0x60, 0xe1, 0x98,
	0x07, 0x52, 0x0b, 0x1c, 0x5e, 0xf1, 0xf4, 0x92, 0x39, 0xd0, 0xcc, 0x04, 0x9e, 0x44, 0x63, 0xad,
	0x70, 0x78, 0xc5, 0x2b, 0xd7, 0x8a, 0x21, 0x30, 0xc4, 0x31, 0x99, 0x85, 0x18, 0xb4, 0xdc, 0x5f,
	0x03, 0xa0, 0x8b, 0xc1, 0x97, 0x93, 0x0c, 0xbb, 0x6f, 0xca, 0xe1, 0xab, 0x2e, 0x79, 0xf5, 0xaf,
	0xc5, 0xa5, 0xc4, 0x51, 0x46, 0x19, 0x57, 0x75, 0x9a, 0xae, 0xd9, 0x1e, 0x5c, 0xcb, 0x50, 0xf8,
	0x52, 0x4c, 0xfc, 0x6a, 0xe2, 0x34, 0x16, 0x4d, 0x9c, 0xf5, 0x0c, 0xc5, 0xb1, 0x98, 0x1c, 0x6b,
	0x7c, 0xf7, 0x97, 0x06, 0xc0, 0xd9, 0x8d, 0xcc, 0xb6, 0x61, 0x8d, 0xc7, 0x71, 0x7a, 0xea, 0xa7,
	0x22, 0x0a, 0xa3, 0xa4, 0xac, 0xb1, 0x4d, 0xb1, 0x57, 0x14, 0x62, 0x37, 0x61, 0x5d, 0x43, 0xb4,
	0x89, 0xab, 0xda, 0x6a, 0xde, 0x4b, 0x1d, 0x3b, 0x03, 0x55, 0xe6, 0x34, 0x6b, 0xa0, 0xd2, 0x32,
	0xaa, 0xa5, 0x70, 0x9c, 0xa5, 0x39, 0x4e, 0x51, 0x2b, 0xba, 0xa5, 0x74, 0xb4, 0x82, 0xf5, 0xa0,
	0x35, 0xe2, 0x63, 0x9f, 0x87, 0x7a, 0xe4, 0xce, 0x3d, 0x5d, 0x73, 0xc4, 0xc7, 0x7b, 0x21, 0xb2,
	0xe7, 0xb0, 0xa9, 0xbf, 0x1f, 0x08, 0x1c, 0x60, 0x22, 0x23, 0x1e, 0xe7, 0xe5, 0x34, 0xee, 0xcc,
	0xb0, 0xf7, 0xd3, 0x34, 0xfe, 0x56, 0x59, 0xce, 0xdb, 0x20, 0xd2, 0xc1, 0x19, 0xa7, 0xfb, 0xa7,
	0x09, 0x6c, 0x76, 0x6c, 0xb2, 0x67, 0x60, 0x0d, 0x30, 0xe6, 0x93, 0xd2, 0x7c, 0x9f, 0x2d, 0x3f,
	0x71, 0xdd, 0x27, 0x8a, 0xe7, 0x69, 0xba, 0xd2, 0xe1, 0x7d, 0xf5, 0x5b, 0xd9, 0xb8, 0xb4, 0xce,
	0x9e, 0xe2, 0x79, 0x9a, 0xde, 0xf9, 0xcd, 0x00, 0x8b, 0x84, 0x99, 0x03, 0xad, 0x0c, 0x45, 0x80,
	0x89, 0x2c, 0xdb, 0xa5, 0x5a, 0xb2, 0x2f, 0xc1, 0x3e, 0x89, 0xc6, 0x38, 0xf0, 0xf5, 0xce, 0x17,
	0x75, 0xca, 0xe1, 0x15, 0x0f, 0x08, 0xaf, 0x75, 0x0f, 0x61, 0x53, 0x95, 0x25, 0xd1, 0x89, 0x29,
	0x35, 0xcc, 0xc5, 0x1a, 0x1b, 0x35, 0x16, 0x29, 0xed, 0x6f, 0xc2, 0x35, 0xf5, 0xcb, 0xaf, 0x25,
	0xa8, 0xe3, 0x3b, 0xef, 0x0d, 0xb0, 0xe8, 0x3c, 0x73, 0xb6, 0xbf, 0x0d, 0x76, 0x28, 0xb2, 0xc0,
	0xcf, 0x25, 0x97, 0x45, 0x3e, 0xb5, 0x16, 0xa8, 0xe0, 0x11, 0xc5, 0x14, 0x44, 0x29, 0xf7, 0x7c,
	0xa4, 0x5f, 0x99, 0xca, 0x64, 0x40, 0xc1, 0xa7, 0xf4, 0xaf, 0x52, 0x42, 0x2a, 0x15, 0x35, 0x74,
	0xac, 0x0a, 0xa2, 0x55, 0x94, 0x19, 0x89, 0x4f, 0x5b, 0xeb, 0x37, 0xe9, 0x50, 0xb7, 0xff, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0x94, 0x07, 0x54, 0xbe, 0xcd, 0x0d, 0x00, 0x00,
}
