// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: policy/v1beta1/cfg.proto

/*
Package v1beta1 is a generated protocol buffer package.

It is generated from these files:
	policy/v1beta1/cfg.proto
	policy/v1beta1/http_response.proto
	policy/v1beta1/type.proto
	policy/v1beta1/value_type.proto

It has these top-level messages:
	AttributeManifest
	Rule
	Action
	Instance
	Handler
	Connection
	Sampling
	RandomSampling
	RateLimitSampling
	FractionalPercent
	Authentication
	Tls
	OAuth
	Mutual
	DirectHttpResponse
	Value
	IPAddress
	Duration
	TimeStamp
	DNSName
	EmailAddress
	Uri
*/
package v1beta1

import bytes "bytes"
import jsonpb "github.com/gogo/protobuf/jsonpb"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler supporting oneof fields for Authentication
func (this *Authentication) MarshalJSON() ([]byte, error) {
	str, err := CfgMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Authentication
func (this *Authentication) UnmarshalJSON(b []byte) error {
	return CfgUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler supporting oneof fields for Tls
func (this *Tls) MarshalJSON() ([]byte, error) {
	str, err := CfgMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler supporting oneof fields for Tls
func (this *Tls) UnmarshalJSON(b []byte) error {
	return CfgUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	CfgMarshaler   = &jsonpb.Marshaler{}
	CfgUnmarshaler = &jsonpb.Unmarshaler{}
)
