// Code generated by protoc-gen-alias. DO NOT EDIT.
package v1

import "istio.io/api/networking/v1alpha3"

type Sidecar = v1alpha3.Sidecar
type IstioIngressListener = v1alpha3.IstioIngressListener
type IstioEgressListener = v1alpha3.IstioEgressListener
type WorkloadSelector = v1alpha3.WorkloadSelector
type OutboundTrafficPolicy = v1alpha3.OutboundTrafficPolicy
type OutboundTrafficPolicy_Mode = v1alpha3.OutboundTrafficPolicy_Mode

const OutboundTrafficPolicy_REGISTRY_ONLY OutboundTrafficPolicy_Mode = v1alpha3.OutboundTrafficPolicy_REGISTRY_ONLY
const OutboundTrafficPolicy_ALLOW_ANY OutboundTrafficPolicy_Mode = v1alpha3.OutboundTrafficPolicy_ALLOW_ANY

type SidecarPort = v1alpha3.SidecarPort
type CaptureMode = v1alpha3.CaptureMode

const CaptureMode_DEFAULT CaptureMode = v1alpha3.CaptureMode_DEFAULT
const CaptureMode_IPTABLES CaptureMode = v1alpha3.CaptureMode_IPTABLES
const CaptureMode_NONE CaptureMode = v1alpha3.CaptureMode_NONE
